version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    working_dir: /app
    command: sh ./mvnw spring-boot:run

volumes:
  maven_cache: